version: '3'
networks: 
  minhvt-network:
    external: true
services:
  minhvt-cukcuk:
    image: minhvt-cukcuk
    container_name: minhvt-cukcuk
    restart: always
    networks:
      - minhvt-network
    ports:
      - '8003:80'
    build:
      context: .
      dockerfile: MISA.CukCuk.Web/Dockerfile